// SQUID
export const CREATE_PROJECT = "CREATE_PROJECT";
export const LATLONG_TO_LATLONG_INIT = "LATLONG_TO_LATLONG_INIT";
export const LATLONG_TO_LATLONG_SUCCESS = "LATLONG_TO_LATLONG_SUCCESS";
export const LATLONG_TO_LATLONG_FAILURE = "LATLONG_TO_LATLONG_FAILURE";

//MARS
export const AUTHENTICATED = "AUTHENTICATED_USER";
export const UNAUTHENTICATED = "UNAUTHENTICATED_USER";
export const AUTHENTICATION_ERROR = "AUTHENTICATION_ERROR";
export const CHANGE_MAP_FILE = "CHANGE_MAP_FILE";
export const CHANGE_SOURCE_FILE = "CHANGE_SOURCE_FILE";
export const INITIALIZE_SAMPLES = "INITIALIZE_SAMPLES";
export const UPLOAD_REQUEST = "UPLOAD_REQUEST";
export const UPLOAD_SUCCESS = "UPLOAD_SUCCESS";
export const UPLOAD_FAILURE = "UPLOAD_FAILURE";
export const FETCH_USER = "FETCH_USER";
export const FETCH_SAMPLES = "FETCH_SAMPLES";
